# This is a basic workflow to help you get started with Actions

name: Auto spigotmc with buildTools

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      # Set up java jdk
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '21'
      # Runs a single command using the runners shell
      - name: get BuildTools
        run: |
           curl -O https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
           mkdir p
           cp BuildTools.jar p/BuildTools.jar

      # Runs a set of commands using the runners shell
      - name: Build
        run: |
          ls
          java --version
          cd p
          java -jar BuildTools.jar --rev 1.21.4
      - name: up
        uses: actions/upload-artifact@v4.6.2
        with:
          name: spigot1.21.4
          path: p/*.jar
